### ISSUE TITLE
kindle-stylesheet.xsl missing for kindle target

### ISSUE THREAD

**Issue by atomicbeecz** [radiodoc/uv-5r#48]
Tried to build kindle target with
```
make kindle
```

But ended with exception, where is missing kindle-stylesheet.xsl 

```
SEVERE: Exception
java.io.FileNotFoundException: Error: xsl file /home/bzz/uv-5r/../toolchain/kindle-stylesheet.xsl not found
	at org.apache.fop.cli.CommandLineOptions.checkSettings(CommandLineOptions.java:965)
	at org.apache.fop.cli.CommandLineOptions.parse(CommandLineOptions.java:172)
	at org.apache.fop.cli.Main.startFOP(Main.java:161)
	at org.apache.fop.cli.Main.main(Main.java:208)

make: *** [../toolchain/Makefile.base:70: kindle] Error 1
```

Where I can get this file pls?

**Comment by z3r0burn** [comment]
I am seeing the same error. After following the path to where the files live I am not able to see the kindle-stylesheet.xsl anywhere in the directory structure. Please release the kindle files needed to build this.
